#!/usr/bin/env sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/dotfiles-arch/scripts/update-monitor.sh

nitrogen --restore

bspc config active_border_color "#283143"
bspc config border_width         2
bspc config window_gap          0
# bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 rezize_corner

bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

"$HOME/.config/polybar/launch.sh" &
